/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisplayMatchCodeRouteImport } from './routes/display.$matchCode'
import { Route as AuthenticatedThemesRouteImport } from './routes/_authenticated/themes'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOperatorsRouteImport } from './routes/_authenticated/operators'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMatchesIndexRouteImport } from './routes/_authenticated/matches.index'
import { Route as AuthenticatedMatchesCreateRouteImport } from './routes/_authenticated/matches.create'
import { Route as AuthenticatedControllerMatchCodeRouteImport } from './routes/_authenticated/controller.$matchCode'
import { Route as AuthenticatedMatchesIdResultRouteImport } from './routes/_authenticated/matches.$id.result'
import { Route as AuthenticatedMatchesIdEditRouteImport } from './routes/_authenticated/matches.$id.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayMatchCodeRoute = DisplayMatchCodeRouteImport.update({
  id: '/display/$matchCode',
  path: '/display/$matchCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedThemesRoute = AuthenticatedThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorsRoute = AuthenticatedOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMatchesIndexRoute =
  AuthenticatedMatchesIndexRouteImport.update({
    id: '/matches/',
    path: '/matches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchesCreateRoute =
  AuthenticatedMatchesCreateRouteImport.update({
    id: '/matches/create',
    path: '/matches/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControllerMatchCodeRoute =
  AuthenticatedControllerMatchCodeRouteImport.update({
    id: '/controller/$matchCode',
    path: '/controller/$matchCode',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchesIdResultRoute =
  AuthenticatedMatchesIdResultRouteImport.update({
    id: '/matches/$id/result',
    path: '/matches/$id/result',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchesIdEditRoute =
  AuthenticatedMatchesIdEditRouteImport.update({
    id: '/matches/$id/edit',
    path: '/matches/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/operators': typeof AuthenticatedOperatorsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/themes': typeof AuthenticatedThemesRoute
  '/display/$matchCode': typeof DisplayMatchCodeRoute
  '/controller/$matchCode': typeof AuthenticatedControllerMatchCodeRoute
  '/matches/create': typeof AuthenticatedMatchesCreateRoute
  '/matches/': typeof AuthenticatedMatchesIndexRoute
  '/matches/$id/edit': typeof AuthenticatedMatchesIdEditRoute
  '/matches/$id/result': typeof AuthenticatedMatchesIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/operators': typeof AuthenticatedOperatorsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/themes': typeof AuthenticatedThemesRoute
  '/display/$matchCode': typeof DisplayMatchCodeRoute
  '/controller/$matchCode': typeof AuthenticatedControllerMatchCodeRoute
  '/matches/create': typeof AuthenticatedMatchesCreateRoute
  '/matches': typeof AuthenticatedMatchesIndexRoute
  '/matches/$id/edit': typeof AuthenticatedMatchesIdEditRoute
  '/matches/$id/result': typeof AuthenticatedMatchesIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/operators': typeof AuthenticatedOperatorsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/themes': typeof AuthenticatedThemesRoute
  '/display/$matchCode': typeof DisplayMatchCodeRoute
  '/_authenticated/controller/$matchCode': typeof AuthenticatedControllerMatchCodeRoute
  '/_authenticated/matches/create': typeof AuthenticatedMatchesCreateRoute
  '/_authenticated/matches/': typeof AuthenticatedMatchesIndexRoute
  '/_authenticated/matches/$id/edit': typeof AuthenticatedMatchesIdEditRoute
  '/_authenticated/matches/$id/result': typeof AuthenticatedMatchesIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/history'
    | '/operators'
    | '/settings'
    | '/themes'
    | '/display/$matchCode'
    | '/controller/$matchCode'
    | '/matches/create'
    | '/matches/'
    | '/matches/$id/edit'
    | '/matches/$id/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/history'
    | '/operators'
    | '/settings'
    | '/themes'
    | '/display/$matchCode'
    | '/controller/$matchCode'
    | '/matches/create'
    | '/matches'
    | '/matches/$id/edit'
    | '/matches/$id/result'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/operators'
    | '/_authenticated/settings'
    | '/_authenticated/themes'
    | '/display/$matchCode'
    | '/_authenticated/controller/$matchCode'
    | '/_authenticated/matches/create'
    | '/_authenticated/matches/'
    | '/_authenticated/matches/$id/edit'
    | '/_authenticated/matches/$id/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DisplayMatchCodeRoute: typeof DisplayMatchCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/$matchCode': {
      id: '/display/$matchCode'
      path: '/display/$matchCode'
      fullPath: '/display/$matchCode'
      preLoaderRoute: typeof DisplayMatchCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/themes': {
      id: '/_authenticated/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof AuthenticatedThemesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operators': {
      id: '/_authenticated/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof AuthenticatedOperatorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches/': {
      id: '/_authenticated/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof AuthenticatedMatchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches/create': {
      id: '/_authenticated/matches/create'
      path: '/matches/create'
      fullPath: '/matches/create'
      preLoaderRoute: typeof AuthenticatedMatchesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/controller/$matchCode': {
      id: '/_authenticated/controller/$matchCode'
      path: '/controller/$matchCode'
      fullPath: '/controller/$matchCode'
      preLoaderRoute: typeof AuthenticatedControllerMatchCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches/$id/result': {
      id: '/_authenticated/matches/$id/result'
      path: '/matches/$id/result'
      fullPath: '/matches/$id/result'
      preLoaderRoute: typeof AuthenticatedMatchesIdResultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches/$id/edit': {
      id: '/_authenticated/matches/$id/edit'
      path: '/matches/$id/edit'
      fullPath: '/matches/$id/edit'
      preLoaderRoute: typeof AuthenticatedMatchesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedOperatorsRoute: typeof AuthenticatedOperatorsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedThemesRoute: typeof AuthenticatedThemesRoute
  AuthenticatedControllerMatchCodeRoute: typeof AuthenticatedControllerMatchCodeRoute
  AuthenticatedMatchesCreateRoute: typeof AuthenticatedMatchesCreateRoute
  AuthenticatedMatchesIndexRoute: typeof AuthenticatedMatchesIndexRoute
  AuthenticatedMatchesIdEditRoute: typeof AuthenticatedMatchesIdEditRoute
  AuthenticatedMatchesIdResultRoute: typeof AuthenticatedMatchesIdResultRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedOperatorsRoute: AuthenticatedOperatorsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedThemesRoute: AuthenticatedThemesRoute,
  AuthenticatedControllerMatchCodeRoute: AuthenticatedControllerMatchCodeRoute,
  AuthenticatedMatchesCreateRoute: AuthenticatedMatchesCreateRoute,
  AuthenticatedMatchesIndexRoute: AuthenticatedMatchesIndexRoute,
  AuthenticatedMatchesIdEditRoute: AuthenticatedMatchesIdEditRoute,
  AuthenticatedMatchesIdResultRoute: AuthenticatedMatchesIdResultRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DisplayMatchCodeRoute: DisplayMatchCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
